name: Skeleton CI Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo start
        run: echo "CI skeleton is working!"

      - name: Simulate DB Check
        run: |
          echo "Checking database connectivity..."
          echo "Database OK"

      - name: Simulate User Check
        run: |
          echo "Verifying user exists..."
          echo "User check passed"
