name: CI/CD Pipeline

on:
  push:
    branches: [main, vrichardo]
  pull_request:
    branches: [main, vrichardo]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
